### ISSUE TITLE
make version 6 available on Pursuit instead of 5

### ISSUE THREAD

**Issue by joopringelberg** [purescript-contrib/purescript-aff-coroutines#18]
Pursuit gives access to version 5.0.0 and version 7.0.0. However, version 5 contains three small coding errors that have been repaired in 6 (6 can be obtained through Bower).
Regards, Joop

**Comment by thomashoneyman** [comment]
I've been unable to publish 6.0.0 due to a disallowed self-import in purescript-contravariant. I'm going to close this as folks using the latest two major versions of the PureScript compiler must be on 7.0.0 anyway.

However, as a note, anyone can publish a tagged version of a library to Pursuit -- if you were using v6.0.0 without issue then you can run `pulp publish` with that version checked out to upload the documentation to Pursuit. Thanks!
